### ISSUE TITLE
Container inside card view with background resource throws error

### ISSUE THREAD

**Issue by mreil617** [developer-shivam/Crescento#4]
ERROR:
`java.lang.IllegalArgumentException: path must be convex
                                                                               at android.graphics.Outline.setConvexPath(Outline.java:264)
                                                                               at developer.shivam.crescento.Container$1.getOutline(Container.java:100)
                                                                               at android.view.View.rebuildOutline(View.java:13079)
                                                                               at android.view.View.sizeChange(View.java:17769)
                                                                               at android.view.View.setFrame(View.java:17726)
                                                                               at android.view.View.layout(View.java:17634)`

XML:
`
<android.support.v7.widget.CardView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@drawable/top_corners_12dp">

                    <developer.shivam.crescento.Container
                        android:layout_width="match_parent"
                        android:layout_height="0dp"
                        android:layout_weight="1"
                        app:curvature="35dp"
                        app:gravity="top">

                        <ImageView 
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:scaleType="centerCrop"
                            android:background="@color/someColor" />

                    </developer.shivam.crescento.Container>
                </android.support.v7.widget.CardView>
`

**Comment by developer-shivam** [comment]
Fixed!
