### ISSUE TITLE
ColorDrawable cannot be cast to BitmapDrawable

### ISSUE THREAD

**Issue by NayanaRBhoj** [developer-shivam/Crescento#9]
Hello, I am getting following issue,

java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Comment by developer-shivam** [comment]
How are you using. Also please share the full stacktrace.

**Comment by wangshanhai** [comment]
Me too，as this----->
  Caused by: java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                                at developer.shivam.crescento.CrescentoImageView.init(CrescentoImageView.java:175)
                                                                                at developer.shivam.crescento.CrescentoImageView.<init>(CrescentoImageView.java:107)

**Comment by Arunkrishna008** [comment]
Me too 

Caused by: java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
at developer.shivam.crescento.CrescentoImageView.init(CrescentoImageView.java:175)
at developer.shivam.crescento.CrescentoImageView.(CrescentoImageView.java:107)

**Comment by developer-shivam** [comment]
Resolved

**Comment by Arunkrishna008** [comment]
i changed the launcher activity ,simple one to mainactivity. when i got an error like

FATAL EXCEPTION: main
                                                                            Process: developer.shivam.crescento, PID: 18298
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{developer.shivam.crescento/developer.shivam.crescento.MainActivity}: android.view.InflateException: Binary XML file line #0: developer.shivam.crescento.CrescentoImageView cannot be cast to android.view.ViewGroup
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: developer.shivam.crescento.CrescentoImageView cannot be cast to android.view.ViewGroup
                                                                             Caused by: java.lang.ClassCastException: developer.shivam.crescento.CrescentoImageView cannot be cast to android.view.ViewGroup
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                at developer.shivam.crescento.MainActivity.onCreate(MainActivity.java:14)
                                                                                at android.app.Activity.performCreate(Activity.java:6672)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
